export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const REGISTER_REQUEST = 'REGISTRO_REQUEST';
export const REGISTER_SUCCESS = 'REGISTRO_SUCCESS';
export const REGISTER_FAILURE = 'REGISTRO_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';